# Generated by Django 6.1.1 on 2026-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('preferencia', models.CharField(max_length=400)),
            ],
        ),
    ]
